export const copy = {
  app: {
    name: "ProShop",
  },
  nav: {
    cart: "Cart",
    signIn: "Sign In",
    profile: "Profile",
    logout: "Logout",
  },
  home: {
    title: "Latest Products",
    loading: "Loading products...",
  },
  product: {
    goBack: "Go Back",
    reviews: "reviews",
    price: "Price",
    status: "Status",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    addToCart: "Add To Cart",
    description: "Description",
    loading: "Loading product details...",
    qty: "Qty",
  },
  cart: {
    title: "Shopping Cart",
    empty: "Your cart is empty",
    goBack: "Go Back",
    subtotal: "Subtotal",
    items: "items",
    checkout: "Proceed To Checkout",
  },
  login: {
    title: "Login",
    signIn: "Sign In",
    emailAddress: "Email Address",
    enterEmail: "Enter email",
    password: "Password",
    enterPassword: "Enter password",
    newCustomer: "New Customer?",
    register: "Register",
    name: "Name",
    enterName: "Enter name",
    confirmPassword: "Confirm Password",
    enterConfirmPassword: "Enter confirm password",
    allReadyHaveAccount: "Already have an account?",
  },
  shipping: {
    title: "Shipping",
    address: "Address",
    enterAddress: "Enter address",
    city: "City",
    enterCity: "Enter city",
    postalCode: "Postal Code",
    enterPostalCode: "Enter postal code",
    country: "Country",
    enterCountry: "Enter country",
    continue: "Continue",
  },
} as const;
